### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by ch-y-sno** [ch-y-sno/portfolio#90]
## 各種情報
サービスの概要とMVPで検証する事柄：
チームメンバーが決めたお題をもとに写真を撮影して、チーム内やネット上の他のユーザーとシェアしたり、お気に入りの写真やユーザーを探すことができるサービスです。
MVPで検証するのは以下となります。
 - ユーザーの新規登録が問題なくできること
 - ログイン・ログアウトが問題なくできること
 - チームの作成ができること
 - 既存のチームから所属したいチームを探し、参加申請ができること
 - チーム内でお題を作成し、メンバーの作成したお題に対して写真を投稿できること
 - お題に対する投稿がメンバー全員分集まったら、メンバーが投稿した写真を閲覧できること
 - 気に入った写真にいいねをつけ、いいねした写真の一覧を閲覧できること
issue:
- [x] #5 Rails環境構築(Docker)
- [x] #7 デプロイ(fly.io)
- [x] #8 仮トップページの作成
- [x] #9 ユーザー新規登録機能
- [x] #10 ログイン/ログアウト機能
- [x] #12 ユーザープロフィール登録機能
- [x] #13 ユーザープロフィール編集機能
- [x] #14 ユーザーのアバター登録機能
- [x] #15 記事投稿機能（画像登録含む）
- [x] #16 記事の詳細表示機能
- [x] #18 記事の編集機能
- [x] #19 記事の削除機能
- [x] #20 お題の登録（予約投稿）機能
- [x] #21 お題の編集機能
- [x] #22 記事へのコメント機能
- [x] #23 記事へのコメントの編集機能
- [x] #24 記事へのコメントの削除機能
- [x] #25 記事へのいいね機能
- [x] #26 記事へのいいね取消機能
- [x] #27 いいねした記事の一覧表示機能
- [x] #33 チーム作成機能
- [x] #35 チームリーダー登録機能
- [x] #36 チームメンバーの募集・承認機能
- [x] #39 チームの一覧表示機能
- [x] #40 チームページ
- [x] #43 ユーザーページ、チームページ、一覧画面でのタグ、コメント、タイトル、ユーザーの検索機能
- [x] #44 "Issueベースの開発"レビュー依頼

サービス名：Snapsquad
サービスURL：https://portfolio-holy-glitter-1455.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [x] 記事投稿機能（画像投稿含む）
- [x] 記事閲覧機能（未ログインでも閲覧可能）
- [x] 記事編集機能
- [x] 記事削除機能
- [x] コメント投稿機能
- [x] コメント閲覧機能（未ログインでも閲覧可能）
- [x] コメント編集機能
- [x] コメント削除機能
- [ ] タグ投稿機能
- [ ] タグ編集機能
- [ ] タグ削除機能
- [x] 記事へのいいね機能
- [x] 記事へのいいね解除機能
- [ ] ユーザーのブックマーク機能
- [ ] ユーザーのブックマーク解除機能
- [ ] チームのブックマーク機能
- [ ] チームのブックマーク解除機能
- [x] 写真撮影のお題の投稿機能
- [ ] お題投稿時の注意表示（権利侵害になりそうなお題にしない、など）
- [ ] 投稿締め切り日時の指定
- [x] ユーザーグループ作成機能
- [x] グループのプロフィール
- [x] グループメンバーの募集機能
- [x] グループへの参加申請・承認機能
- [ ] グループの解散機能
- [ ] 写真の公開・非公開設定
- [x] ユーザーのプロフィール編集機能（サムネイル投稿含む）
- [ ] グループ内でのチャット機能
- [x] コメント、タイトル、ユーザー等の検索機能
- [ ] 新着情報の通知機能
- [ ] 画像の自動サイズ調整機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください。なければこの項目は省略してください。
MVPリリース時点で作らなくなった機能:
 - パスワード変更機能
 - メールアドレス変更機能
 - チームの解散機能
 - チーム退会機能
 - アカウントの削除機能
 - 写真の公開・非公開設定
 - タグ投稿機能
 - タグ編集機能
 - タグ削除機能
 - ユーザーのブックマーク機能
 - ユーザーのブックマーク解除機能
 - チームのブックマーク機能
 - チームのブックマーク解除機能
 - お題投稿時の注意表示（権利侵害になりそうなお題にしない、など）
 - 投稿締め切り日時の指定
 - グループ内でのチャット機能
 - 新着情報の通知機能
 - 画像の自動サイズ調整機能
*上記はissueベースの開発レビュー依頼時に、MVPリリース時点で実装する機能から外しました。
 本リリース時には実装する予定です。
*その他本リリース時に実装予定のもの：Rspec, CSS調整, モーダル・ダークモード修正, 条件分岐・ネスト等見直し, slim, S3 (現状fly.io volumesを使用しており、アップロードした画像の表示が不安定です。)

追加した機能:
 - ログイン、メンバー申請、ユーザーメニューのモーダルの実装
 - ダークモードの実装 (現状不具合あり。本リリースまでに修正。)
 - 画像投稿時のプレビュー表示
 - コメント・お題の編集のajax化

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有してください。

- [ ] トップ画面
 ![Image](https://github.com/user-attachments/assets/d31fa042-5edf-48ae-840d-68b106a8b1a4)

- [ ] ログイン機能
 ![Image](https://github.com/user-attachments/assets/ed12b909-48a5-4dea-9ad7-3cbbc7eeb0d6)

- [ ] ユーザー登録機能
![Image](https://github.com/user-attachments/assets/1a99b36b-3ce7-4ba1-afa6-0303be1623ef)

- [ ] プロフィール設定機能: 年齢・自己紹介など詳しいプロフィールの設定ができます。
![Image](https://github.com/user-attachments/assets/108c22c3-ec85-488d-8833-f8a2278adff6)

- [ ] チーム作成機能: チームを作成してメンバーを募集したり、既存のチームに参加できます。
 ![Image](https://github.com/user-attachments/assets/8b4d8070-580a-414c-890f-de1bd7f1fbde)

- [ ] チームリーダーによるチーム管理機能: チームのルールやメンバーから出題されたお題、メンバー申請の管理ができます。
![Image](https://github.com/user-attachments/assets/3fc1b5a4-0daf-4176-be7f-7c6d2051070f)

- [ ] チームメンバー募集・申請・承認機能: ユーザーは参加したいチームに参加申請でき、チームリーダーは申請を承認または拒否することができます。
![Image](https://github.com/user-attachments/assets/cdeb34f7-64cd-420a-b563-d9a02b1a37d2)

- [ ] チームページ: チームのリーダー(作成者)と承認されたメンバー、チームの作品などの情報が一覧表示されます。
![Image](https://github.com/user-attachments/assets/42430e43-53d7-47e8-bf16-476b91654f29)

- [ ] お題への写真投稿機能: チームは写真撮影のお題を出題でき、メンバーはお題に対して作品を投稿できます。
 ![Image](https://github.com/user-attachments/assets/9778e371-28a4-4120-8d76-38b0d32513a6)

- [ ] お題への投稿一覧機能: ひとつのお題にチームの全てのメンバーが写真を投稿し終わると、メンバーの投稿した画像が一覧表示されます。いいねが多い順に表示されます。
![Image](https://github.com/user-attachments/assets/596f25e3-0e40-4809-8981-7e69b4c61a53)

- [ ] 投稿内容閲覧・編集・削除機能: 投稿した写真やキャプションの編集をしたり、他のユーザーの作品にいいねできます。
 ![Image](https://github.com/user-attachments/assets/fd9644e6-77a7-495d-82c0-e27ca85f7f90)

- [ ] 投稿された写真へのコメント、コメントの編集・削除機能
![Image](https://github.com/user-attachments/assets/11e2404a-8c8b-4656-be69-bdbfc0672fc7)

- [ ] いいねした写真一覧表示機能
![Image](https://github.com/user-attachments/assets/641f168b-07db-4559-8fb4-662e21f0354a)

- [ ] ユーザーページ: ユーザーの活動履歴のページです。
![Image](https://github.com/user-attachments/assets/1b4a3aac-4935-4f2b-bb30-3662e058a3ea)

**Comment by TakenakaEri** [comment]
内容を確認しました。
現状、以下のように写真が見えない状態です。外部ストレージは何を使用していますでしょうか？

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/9f7825604f856b63476fff24416d6e74.png)](https://startup-technology.gyazo.com/9f7825604f856b63476fff24416d6e74)

画像を表示できるようにして、再提出をお願いします。

**Comment by ch-y-sno** [comment]
竹中様

お世話になります。本件早速レビューいただきありがとうござます。

画像が表示されない不具合につきまして、大変失礼いたしました。
本アプリはfly.ioにてデプロイしており、外部ストレージはfly.ioのvolumesを使用しておりました。
本ストレージの性質上(または私の設定ミスのため)、一定期間経過後に画像が消えてしまうなどの不具合が起きておりました。
解決策として、外部ストレージをAmazon S3へ変更いたしました。

再度レビューをお願いできますでしょうか。
何卒よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
